# build file for the ant
# last byte is always 00 for ants
from random import randrange

# set up the id
MAX_ID = 65536 # FF FF
INCREMENTATION = 1
NUM_BYTES = 2
# MAX_DELAY = 200
# MIN_DELAY = 60

current_val = 1;
print "############# GENERATING ANT ############# "

# read in the current id
with open("id.c") as f:
  data = f.read().split("\n")[4:] # skip the first 5 lines
  val = ""
  for i, line in enumerate(reversed(data)):
    if len(line) > 1 and i > 1:
      # parse out the hex
      val += line.split(" ")[2].replace("0x", "")#.decode("hex")
    
  current_val = int(val, 16)
  print "The current value is: ", current_val

# increment the current val
current_val += INCREMENTATION
if current_val > MAX_ID: current_val = 0 # wrap around
print "Incrementing id to: ", current_val
new_val = hex(current_val).replace("0x", "").upper()

# pad current value up to 5 bytes long
if len(new_val) < NUM_BYTES*2:
  i = NUM_BYTES*2 - len(new_val) 
  while i > 0:
    new_val = "0"+new_val
    i -= 1

# split up current val into an array
print "HEX ID: ", new_val
new_val = [new_val[i:i+2] for i in range(0, len(new_val), 2)]

with open('id.c', 'w') as f:

  f.write("""/*
  * THIS IS AN AUTOGENERATED FILE.
  * DO NOT TOUCH.
  */

""")
  hex_id = []
  i = 1
  for val in reversed(new_val):
    if len(val) == 1: val = "0" + val 
    f.write("#define ID_" + str(i) + " 0x"+str(val) + "\n")
    i += 1

  # pad the rest with zeros
  while i < NUM_BYTES - i:
    f.write("#define ID_" + str(i) + " 0x00\n")
    i += 1

  ms_delay = current_val % 40
  max_payload = 3 + current_val % 3
  print "MS DELAY: ", ms_delay
  print "MAX PAYLOAD: ", max_payload
  # write in the us delay
  f.write("#define MS_DELAY "+ str(ms_delay) + "\n")
  f.write("#define MAX_PAYLOAD "+ str(max_payload))